name = "ClientSidePlus"
author = "MrBroggle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f5b88b643f08a7feef3a8926d8b8c799733319c75f34fc05a9672ff1757c694"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
